export const STYLE_PRESETS = {
  'Upper Dynamic': {
    presetName: 'Upper Dynamic',
    tagline: 'Electric blue spotlight gradient with drop shadow',
    tags: ['Reveal', 'Dynamic', 'Trending'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#00B4D8',
    activeWordScale: 1.18,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'sentence',
    highlightType: 'spotlight',
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 14,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasNeonGlow: true,
    neonColor: '#00B4D8',
    neonIntensity: 18,
    animationPreset: 'pop',
    position: 'middle',
    verticalPositionPercent: 58,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 1.0,
    lineSpacing: 1.18,
    textTransform: 'none',
    density: 'balanced',
  },
  'Dynamic Karaoke': {
    presetName: 'Dynamic Karaoke',
    tagline: 'Vibrant yellow active highlight synchronized to speech',
    tags: ['Karaoke', 'Smooth'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 32,
    fontWeight: '800',
    textColor: '#E2E8F0',
    textOpacity: 1.0,
    activeWordColor: '#FFE600',
    activeWordScale: 1.12,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'karaoke',
    backgroundColor: '#090d16',
    backgroundOpacity: 0.65,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 10,
    outlineColor: '#000000',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 12,
    animationPreset: 'bounce',
    position: 'middle',
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 86,
    letterSpacing: 0.8,
    lineSpacing: 1.2,
    textTransform: 'none',
    density: 'balanced',
  },
  'Hormozi Pop': {
    presetName: 'Hormozi Pop',
    tagline: 'Aggressive uppercase with 4px black stroke and bounce',
    tags: ['Viral', 'High Impact'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 36,
    fontWeight: '900',
    textColor: '#FFE600',
    textOpacity: 1.0,
    activeWordColor: '#10FF70',
    activeWordScale: 1.2,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 8,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 15,
    animationPreset: 'pop',
    position: 'middle',
    verticalPositionPercent: 60,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 1.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    density: 'compact',
  },
  'Highlight Pill': {
    presetName: 'Highlight Pill',
    tagline: 'Animated traveling background pill over active word',
    tags: ['Pill', 'Clean'],
    fontFamily: 'Poppins, sans-serif',
    fontSize: 30,
    fontWeight: '800',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#000000',
    activeWordScale: 1.08,
    activeWordBackground: '#10FF70',
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'pill',
    backgroundColor: '#05070d',
    backgroundOpacity: 0.75,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 14,
    outlineColor: '#000000',
    outlineWidth: 1,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.7)',
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#10FF70',
    neonIntensity: 14,
    animationPreset: 'bounce',
    position: 'bottom',
    verticalPositionPercent: 78,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 0.6,
    lineSpacing: 1.2,
    textTransform: 'none',
    density: 'balanced',
  },
  'Electric Lime': {
    presetName: 'Electric Lime',
    tagline: 'Aggressive heavy Anton with neon green radiance',
    tags: ['MrBeast', 'Punchy'],
    fontFamily: 'Anton, sans-serif',
    fontSize: 38,
    fontWeight: '800',
    textColor: '#10FF70',
    textOpacity: 1.0,
    activeWordColor: '#FFFFFF',
    activeWordScale: 1.16,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'scale',
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 6,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#10FF70',
    shadowBlur: 18,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#10FF70',
    neonIntensity: 20,
    animationPreset: 'bounce',
    position: 'middle',
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.0,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    density: 'compact',
  },
  'Cyberpunk Neon': {
    presetName: 'Cyberpunk Neon',
    tagline: 'Radiant cyan glow bloom with dark violet contrast',
    tags: ['Neon', 'Futuristic'],
    fontFamily: 'Russo One, sans-serif',
    fontSize: 32,
    fontWeight: '700',
    textColor: '#00F0FF',
    textOpacity: 1.0,
    activeWordColor: '#FF007F',
    activeWordScale: 1.15,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'neon',
    backgroundColor: '#070a14',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 10,
    outlineColor: '#050515',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#00F0FF',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#00F0FF',
    neonIntensity: 24,
    animationPreset: 'pop',
    position: 'middle',
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.5,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    density: 'balanced',
  },
  'Golden Fire': {
    presetName: 'Golden Fire',
    tagline: 'Amber gold spotlight with flame aura',
    tags: ['Cinematic', 'Flame'],
    fontFamily: 'Bebas Neue, sans-serif',
    fontSize: 40,
    fontWeight: '400',
    textColor: '#FFB800',
    textOpacity: 1.0,
    activeWordColor: '#FFFFFF',
    activeWordScale: 1.2,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'spotlight',
    backgroundColor: '#130800',
    backgroundOpacity: 0.8,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    outlineColor: '#FF4800',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#FF5500',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#FF6A00',
    neonIntensity: 22,
    animationPreset: 'zoom',
    position: 'bottom',
    verticalPositionPercent: 80,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 2.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    density: 'balanced',
  },
  'Glitch Cyberpunk': {
    presetName: 'Glitch Cyberpunk',
    tagline: 'Subtle RGB chromatic displacement on word entrance',
    tags: ['Glitch', 'Edgy'],
    fontFamily: 'Syne, sans-serif',
    fontSize: 34,
    fontWeight: '800',
    textColor: '#F8FAFC',
    textOpacity: 1.0,
    activeWordColor: '#00F0FF',
    activeWordScale: 1.14,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'glitch',
    backgroundColor: '#0B0F19',
    backgroundOpacity: 0.88,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 12,
    outlineColor: '#EF4444',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0, 240, 255, 0.6)',
    shadowBlur: 14,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    hasNeonGlow: true,
    neonColor: '#00F0FF',
    neonIntensity: 18,
    animationPreset: 'glitch',
    position: 'middle',
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.2,
    lineSpacing: 1.15,
    textTransform: 'none',
    density: 'compact',
  },
  'Social Viral': {
    presetName: 'Social Viral',
    tagline: 'Clean white with bold drop shadow (Reels / Shorts)',
    tags: ['TikTok', 'Clean'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#38BDF8',
    activeWordScale: 1.15,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#000000',
    shadowBlur: 14,
    shadowOffsetX: 3,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#38BDF8',
    neonIntensity: 10,
    animationPreset: 'pop',
    position: 'custom',
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 82,
    letterSpacing: 1.0,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    density: 'compact',
  },
  'Typewriter': {
    presetName: 'Typewriter',
    tagline: 'Progressive character reveal synced to speech timing',
    tags: ['Typewriter', 'Story'],
    fontFamily: 'Roboto Mono, monospace',
    fontSize: 28,
    fontWeight: '700',
    textColor: '#10FF70',
    textOpacity: 1.0,
    activeWordColor: '#FFFFFF',
    activeWordScale: 1.05,
    activeWordBackground: null,
    activeWordBgRadius: 4,
    spotlightCase: 'normal',
    normalWordCase: 'normal',
    highlightType: 'reveal',
    backgroundColor: '#020617',
    backgroundOpacity: 0.9,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 6,
    outlineColor: '#000000',
    outlineWidth: 1,
    hasShadow: true,
    shadowColor: 'rgba(16, 255, 112, 0.4)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasNeonGlow: true,
    neonColor: '#10FF70',
    neonIntensity: 12,
    animationPreset: 'fade',
    position: 'bottom',
    verticalPositionPercent: 82,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 0.5,
    lineSpacing: 1.2,
    textTransform: 'none',
    density: 'balanced',
  },
  'Minimal Premium': {
    presetName: 'Minimal Premium',
    tagline: 'High-end luxury typography with subtle transitions',
    tags: ['Luxury', 'Minimal'],
    fontFamily: 'Inter, sans-serif',
    fontSize: 26,
    fontWeight: '600',
    textColor: '#F8FAFC',
    textOpacity: 0.95,
    activeWordColor: '#93C5FD',
    activeWordScale: 1.06,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    spotlightCase: 'normal',
    normalWordCase: 'normal',
    highlightType: 'karaoke',
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.55,
    hasBackgroundBox: true,
    backgroundPadding: 8,
    borderRadius: 8,
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#93C5FD',
    neonIntensity: 6,
    animationPreset: 'fade',
    position: 'bottom',
    verticalPositionPercent: 85,
    alignment: 'center',
    maxWidthPercent: 86,
    letterSpacing: 0.6,
    lineSpacing: 1.25,
    textTransform: 'none',
    density: 'relaxed',
  }
};

export const formatSeconds = (seconds) => {
  if (isNaN(seconds) || seconds < 0) return '00:00:00.000';
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

export const parseTimestamp = (timeString) => {
  if (!timeString) return 0;
  const parts = timeString.split(':');
  if (parts.length === 3) {
    const hrs = parseFloat(parts[0]) || 0;
    const mins = parseFloat(parts[1]) || 0;
    const secs = parseFloat(parts[2]) || 0;
    return hrs * 3600 + mins * 60 + secs;
  }
  return parseFloat(timeString) || 0;
};
