// ─────────────────────────────────────────────────────────────────────────────
// PRESET SCHEMA — Full data-driven configuration consumed by both the live
// preview (CaptionOverlay / animationEngine) and the ASS export renderer.
// Add new presets here WITHOUT touching the core rendering engine.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @typedef {Object} AnimationConfig
 * @property {'fade'|'slide-up'|'scale-in'|'bounce'|'elastic'|'spring'|'pop'|'none'} entrance
 * @property {'color'|'scale'|'scale-color'|'glow-pulse'|'bounce-up'|'pill-track'|'none'} activeWord
 * @property {'punch'|'highlight'|'neon-glow'|'bold-pop'|'none'} emphasis
 * @property {'fade'|'slide-down'|'scale-out'|'none'} exit
 * @property {'premium'|'bounce'|'elastic'|'easeOut'|'easeInOut'|'spring'|'linear'} easing
 * @property {number} duration  — ms for entrance transition
 * @property {number} delay     — ms stagger between words
 * @property {number} scale     — entrance/active scale multiplier
 * @property {number} activeScale — active word scale multiplier
 * @property {number} opacity   — entrance start opacity
 * @property {number} translateY — entrance Y offset in px
 * @property {number} translateX — entrance X offset in px
 * @property {number} rotation  — entrance rotation in deg
 * @property {number} blur      — entrance blur in px
 * @property {number} intensity — 0–1 emphasis intensity modifier
 */

// CSS easing curve map — consumed by animationEngine for style injection
export const EASING_CURVES = {
  premium:   'cubic-bezier(0.16, 1, 0.3, 1)',
  bounce:    'cubic-bezier(0.34, 1.56, 0.64, 1)',
  elastic:   'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
  easeOut:   'cubic-bezier(0, 0, 0.2, 1)',
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  spring:    'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
  linear:    'linear',
};

// ─────────────────────────────────────────────────────────────────────────────
// PRESET CATEGORIES
// ─────────────────────────────────────────────────────────────────────────────
export const PRESET_CATEGORIES = ['All', 'Trending', 'Premium', 'Dynamic', 'Podcast'];

export const STYLE_PRESETS = {

  // ───────────────────────── TRENDING ──────────────────────────

  'Viral Pop': {
    presetName: 'Viral Pop',
    category: 'Trending',
    tagline: 'Bold uppercase with active-word scale pop and subtle overshoot',
    tags: ['Viral', 'Trending', 'TikTok'],
    // Typography
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    // Appearance
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#FFE600',
    highlightColor: '#FFE600',
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 14,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    // Layout
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 68,
    alignment: 'center',
    maxWidthPercent: 88,
    // Legacy compat
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.28,
    // Animation
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'bounce',
      duration: 180,
      delay: 30,
      scale: 0.82,
      activeScale: 1.28,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.85,
    },
    animationPreset: 'pop',
    density: 'compact',
  },

  'Dynamic Karaoke': {
    presetName: 'Dynamic Karaoke',
    category: 'Trending',
    tagline: 'Active word changes color with smooth karaoke transition',
    tags: ['Karaoke', 'Smooth', 'Trending'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineSpacing: 1.2,
    textTransform: 'none',
    textColor: '#E2E8F0',
    textOpacity: 1.0,
    activeWordColor: '#FFE600',
    highlightColor: '#FFE600',
    outlineColor: '#000000',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 12,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    backgroundColor: '#090d16',
    backgroundOpacity: 0.65,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 10,
    position: 'middle',
    horizontalPercent: 50,
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.12,
    animation: {
      entrance: 'fade',
      activeWord: 'color',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'premium',
      duration: 220,
      delay: 20,
      scale: 1.0,
      activeScale: 1.12,
      opacity: 0.4,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.7,
    },
    animationPreset: 'bounce',
    density: 'balanced',
  },

  'Punch': {
    presetName: 'Punch',
    category: 'Trending',
    tagline: 'Important words scale up fast with slight overshoot — smooth return',
    tags: ['Viral', 'High Impact', 'Trending'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineSpacing: 1.12,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#FF3D3D',
    highlightColor: '#FF3D3D',
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.95)',
    shadowBlur: 10,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#FF3D3D',
    neonIntensity: 16,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 70,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'scale',
    heroFontWeight: '900',
    activeWordScale: 1.45,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'bounce',
      duration: 120,
      delay: 20,
      scale: 0.7,
      activeScale: 1.45,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 1.0,
    },
    animationPreset: 'pop',
    density: 'compact',
  },

  'Bounce': {
    presetName: 'Bounce',
    category: 'Trending',
    tagline: 'Active word moves upward with subtle scale and smooth elastic return',
    tags: ['Bounce', 'Smooth', 'Trending'],
    fontFamily: 'Poppins, sans-serif',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0.6,
    lineSpacing: 1.2,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#38BDF8',
    highlightColor: '#38BDF8',
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#38BDF8',
    neonIntensity: 12,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 72,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'sentence',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.18,
    animation: {
      entrance: 'slide-up',
      activeWord: 'bounce-up',
      emphasis: 'bold-pop',
      exit: 'fade',
      easing: 'spring',
      duration: 200,
      delay: 25,
      scale: 1.0,
      activeScale: 1.18,
      opacity: 0.0,
      translateY: 12,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.7,
    },
    animationPreset: 'bounce',
    density: 'balanced',
  },

  'Word Zoom': {
    presetName: 'Word Zoom',
    category: 'Trending',
    tagline: 'Active word briefly scales up while surrounding words stay stable',
    tags: ['Zoom', 'Clean', 'Trending'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.8,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#A78BFA',
    highlightColor: '#A78BFA',
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#A78BFA',
    neonIntensity: 14,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 70,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'scale',
    heroFontWeight: '900',
    activeWordScale: 1.35,
    animation: {
      entrance: 'fade',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'premium',
      duration: 160,
      delay: 15,
      scale: 1.0,
      activeScale: 1.35,
      opacity: 0.6,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.8,
    },
    animationPreset: 'zoom',
    density: 'compact',
  },

  'Dynamic Highlight': {
    presetName: 'Dynamic Highlight',
    category: 'Trending',
    tagline: 'Animated background pill follows active word smoothly',
    tags: ['Pill', 'Clean', 'Trending'],
    fontFamily: 'Poppins, sans-serif',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0.6,
    lineSpacing: 1.2,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#000000',
    highlightColor: '#10FF70',
    outlineColor: '#000000',
    outlineWidth: 1,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.7)',
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#10FF70',
    neonIntensity: 14,
    activeWordBackground: '#10FF70',
    activeWordBgRadius: 8,
    backgroundColor: '#05070d',
    backgroundOpacity: 0.75,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 14,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 78,
    alignment: 'center',
    maxWidthPercent: 88,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'pill',
    heroFontWeight: '900',
    activeWordScale: 1.08,
    animation: {
      entrance: 'fade',
      activeWord: 'pill-track',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'premium',
      duration: 180,
      delay: 0,
      scale: 1.0,
      activeScale: 1.08,
      opacity: 0.8,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.6,
    },
    animationPreset: 'bounce',
    density: 'balanced',
  },

  'Hormozi Pop': {
    presetName: 'Hormozi Pop',
    category: 'Trending',
    tagline: 'Aggressive uppercase with 4px black stroke and bounce',
    tags: ['Viral', 'High Impact', 'Trending'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    textColor: '#FFE600',
    textOpacity: 1.0,
    activeWordColor: '#10FF70',
    highlightColor: '#10FF70',
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.95)',
    shadowBlur: 8,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 15,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    position: 'middle',
    horizontalPercent: 50,
    verticalPositionPercent: 60,
    alignment: 'center',
    maxWidthPercent: 88,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.2,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'bounce',
      duration: 150,
      delay: 25,
      scale: 0.85,
      activeScale: 1.2,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.9,
    },
    animationPreset: 'pop',
    density: 'compact',
  },

  // ───────────────────────── PREMIUM ──────────────────────────

  'Hero Spotlight': {
    presetName: 'Hero Spotlight',
    category: 'Premium',
    tagline: 'Signature style: clean white context + gigantic electric blue hero keyword',
    tags: ['Reference', 'Hero', 'Premium'],
    fontFamily: 'Poppins, sans-serif',
    fontSize: 36,
    fontWeight: '600',
    heroFontWeight: '900',
    letterSpacing: 0.5,
    lineSpacing: 1.15,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#3091F7',
    highlightColor: '#3091F7',
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.65)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasNeonGlow: true,
    neonColor: '#3091F7',
    neonIntensity: 14,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'left-chest',
    horizontalPercent: 22,
    verticalPositionPercent: 58,
    alignment: 'left',
    maxWidthPercent: 68,
    spotlightCase: 'uppercase',
    normalWordCase: 'sentence',
    highlightType: 'spotlight',
    activeWordScale: 2.15,
    animation: {
      entrance: 'fade',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'premium',
      duration: 200,
      delay: 15,
      scale: 0.96,
      activeScale: 2.15,
      opacity: 0.0,
      translateY: 6,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.8,
    },
    animationPreset: 'smooth-fade',
    density: 'balanced',
  },

  'Minimal Premium': {
    presetName: 'Minimal Premium',
    category: 'Premium',
    tagline: 'High-end luxury typography with subtle transitions — less is more',
    tags: ['Luxury', 'Minimal', 'Premium'],
    fontFamily: 'Inter, sans-serif',
    fontSize: 26,
    fontWeight: '600',
    letterSpacing: 0.6,
    lineSpacing: 1.25,
    textTransform: 'none',
    textColor: '#F8FAFC',
    textOpacity: 0.95,
    activeWordColor: '#93C5FD',
    highlightColor: '#93C5FD',
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#93C5FD',
    neonIntensity: 6,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.55,
    hasBackgroundBox: true,
    backgroundPadding: 8,
    borderRadius: 8,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 85,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'normal',
    normalWordCase: 'normal',
    highlightType: 'karaoke',
    heroFontWeight: '700',
    activeWordScale: 1.06,
    animation: {
      entrance: 'fade',
      activeWord: 'color',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'easeOut',
      duration: 280,
      delay: 10,
      scale: 1.0,
      activeScale: 1.06,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.4,
    },
    animationPreset: 'fade',
    density: 'relaxed',
  },

  'Cinematic': {
    presetName: 'Cinematic',
    category: 'Premium',
    tagline: 'Elegant typography with slow entrance, subtle scale and soft shadow',
    tags: ['Cinematic', 'Premium', 'Film'],
    fontFamily: 'Bebas Neue, sans-serif',
    fontSize: 38,
    fontWeight: '400',
    letterSpacing: 3.0,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    textColor: '#F1F5F9',
    textOpacity: 1.0,
    activeWordColor: '#FCD34D',
    highlightColor: '#FCD34D',
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 6,
    hasNeonGlow: false,
    neonColor: '#FCD34D',
    neonIntensity: 10,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.35,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 4,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 85,
    alignment: 'center',
    maxWidthPercent: 80,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '700',
    activeWordScale: 1.08,
    animation: {
      entrance: 'fade',
      activeWord: 'color',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'easeInOut',
      duration: 350,
      delay: 40,
      scale: 1.03,
      activeScale: 1.08,
      opacity: 0.0,
      translateY: 4,
      translateX: 0,
      rotation: 0,
      blur: 1,
      intensity: 0.5,
    },
    animationPreset: 'fade',
    density: 'relaxed',
  },

  'Editorial': {
    presetName: 'Editorial',
    category: 'Premium',
    tagline: 'Modern magazine-style typography with controlled spacing',
    tags: ['Magazine', 'Sophisticated', 'Premium'],
    fontFamily: 'Syne, sans-serif',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 2.0,
    lineSpacing: 1.3,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#F472B6',
    highlightColor: '#F472B6',
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.7)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#F472B6',
    neonIntensity: 10,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#0f0f0f',
    backgroundOpacity: 0.6,
    hasBackgroundBox: true,
    backgroundPadding: 14,
    borderRadius: 2,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 84,
    alignment: 'center',
    maxWidthPercent: 78,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.1,
    animation: {
      entrance: 'slide-up',
      activeWord: 'color',
      emphasis: 'bold-pop',
      exit: 'fade',
      easing: 'premium',
      duration: 260,
      delay: 30,
      scale: 1.0,
      activeScale: 1.1,
      opacity: 0.0,
      translateY: 10,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.6,
    },
    animationPreset: 'smooth-fade',
    density: 'balanced',
  },

  'Clean Bold': {
    presetName: 'Clean Bold',
    category: 'Premium',
    tagline: 'Large bold text with subtle active-word animation — always readable',
    tags: ['Clean', 'Bold', 'Premium'],
    fontFamily: 'Inter, sans-serif',
    fontSize: 38,
    fontWeight: '900',
    letterSpacing: 0.3,
    lineSpacing: 1.2,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#60A5FA',
    highlightColor: '#60A5FA',
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#60A5FA',
    neonIntensity: 8,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 72,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'normal',
    normalWordCase: 'sentence',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.1,
    animation: {
      entrance: 'fade',
      activeWord: 'color',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'premium',
      duration: 200,
      delay: 15,
      scale: 1.0,
      activeScale: 1.1,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.5,
    },
    animationPreset: 'fade',
    density: 'balanced',
  },

  // ───────────────────────── DYNAMIC ──────────────────────────

  'Glitch Cyberpunk': {
    presetName: 'Glitch Cyberpunk',
    category: 'Dynamic',
    tagline: 'Subtle RGB chromatic displacement on word entrance — always readable',
    tags: ['Glitch', 'Edgy', 'Dynamic'],
    fontFamily: 'Syne, sans-serif',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 1.2,
    lineSpacing: 1.15,
    textTransform: 'none',
    textColor: '#F8FAFC',
    textOpacity: 1.0,
    activeWordColor: '#00F0FF',
    highlightColor: '#00F0FF',
    outlineColor: '#EF4444',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,240,255,0.6)',
    shadowBlur: 14,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    hasNeonGlow: true,
    neonColor: '#00F0FF',
    neonIntensity: 18,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    backgroundColor: '#0B0F19',
    backgroundOpacity: 0.88,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 12,
    position: 'middle',
    horizontalPercent: 50,
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'normal',
    highlightType: 'glitch',
    heroFontWeight: '900',
    activeWordScale: 1.14,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'elastic',
      duration: 140,
      delay: 20,
      scale: 0.88,
      activeScale: 1.14,
      opacity: 0.0,
      translateY: 0,
      translateX: 3,
      rotation: 0,
      blur: 1,
      intensity: 0.9,
    },
    animationPreset: 'glitch',
    density: 'compact',
  },

  'Elastic': {
    presetName: 'Elastic',
    category: 'Dynamic',
    tagline: 'Word scales with a soft elastic spring effect on entrance',
    tags: ['Elastic', 'Fun', 'Dynamic'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineSpacing: 1.18,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#FB923C',
    highlightColor: '#FB923C',
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#FB923C',
    neonIntensity: 12,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 70,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'scale',
    heroFontWeight: '900',
    activeWordScale: 1.3,
    animation: {
      entrance: 'elastic',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'elastic',
      duration: 200,
      delay: 30,
      scale: 0.5,
      activeScale: 1.3,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.85,
    },
    animationPreset: 'bounce',
    density: 'compact',
  },

  'Slide': {
    presetName: 'Slide',
    category: 'Dynamic',
    tagline: 'Words enter with controlled horizontal movement from left',
    tags: ['Slide', 'Motion', 'Dynamic'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineSpacing: 1.2,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#34D399',
    highlightColor: '#34D399',
    outlineColor: '#000000',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#34D399',
    neonIntensity: 10,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 70,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'normal',
    normalWordCase: 'sentence',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.12,
    animation: {
      entrance: 'slide-up',
      activeWord: 'color',
      emphasis: 'bold-pop',
      exit: 'fade',
      easing: 'premium',
      duration: 220,
      delay: 25,
      scale: 1.0,
      activeScale: 1.12,
      opacity: 0.0,
      translateY: 14,
      translateX: -16,
      rotation: 0,
      blur: 0,
      intensity: 0.65,
    },
    animationPreset: 'bounce',
    density: 'balanced',
  },

  'Jump': {
    presetName: 'Jump',
    category: 'Dynamic',
    tagline: 'Active word makes a subtle vertical jump with spring easing',
    tags: ['Jump', 'Energy', 'Dynamic'],
    fontFamily: 'Poppins, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.8,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#FACC15',
    highlightColor: '#FACC15',
    outlineColor: '#000000',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 5,
    hasNeonGlow: false,
    neonColor: '#FACC15',
    neonIntensity: 12,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 70,
    alignment: 'center',
    maxWidthPercent: 86,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.2,
    animation: {
      entrance: 'scale-in',
      activeWord: 'bounce-up',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'spring',
      duration: 160,
      delay: 20,
      scale: 0.9,
      activeScale: 1.2,
      opacity: 0.0,
      translateY: -10,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.8,
    },
    animationPreset: 'bounce',
    density: 'compact',
  },

  'Neon Glow': {
    presetName: 'Neon Glow',
    category: 'Dynamic',
    tagline: 'Active word receives animated neon glow — cyberpunk energy',
    tags: ['Neon', 'Futuristic', 'Dynamic'],
    fontFamily: 'Russo One, sans-serif',
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 1.5,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    textColor: '#00F0FF',
    textOpacity: 1.0,
    activeWordColor: '#FF007F',
    highlightColor: '#FF007F',
    outlineColor: '#050515',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#00F0FF',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#00F0FF',
    neonIntensity: 24,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    backgroundColor: '#070a14',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 10,
    position: 'middle',
    horizontalPercent: 50,
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'neon',
    heroFontWeight: '900',
    activeWordScale: 1.15,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'bounce',
      duration: 160,
      delay: 20,
      scale: 0.85,
      activeScale: 1.15,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 2,
      intensity: 1.0,
    },
    animationPreset: 'pop',
    density: 'balanced',
  },

  // ───────────────────────── PODCAST ──────────────────────────

  'Podcast Clean': {
    presetName: 'Podcast Clean',
    category: 'Podcast',
    tagline: 'Clean readable transcript style for interview and podcast videos',
    tags: ['Podcast', 'Clean', 'Interview'],
    fontFamily: 'Inter, sans-serif',
    fontSize: 24,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineSpacing: 1.4,
    textTransform: 'none',
    textColor: '#F1F5F9',
    textOpacity: 1.0,
    activeWordColor: '#7DD3FC',
    highlightColor: '#7DD3FC',
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.6)',
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#7DD3FC',
    neonIntensity: 6,
    activeWordBackground: null,
    activeWordBgRadius: 4,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.7,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 6,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 88,
    alignment: 'center',
    maxWidthPercent: 80,
    spotlightCase: 'normal',
    normalWordCase: 'normal',
    highlightType: 'karaoke',
    heroFontWeight: '700',
    activeWordScale: 1.04,
    animation: {
      entrance: 'fade',
      activeWord: 'color',
      emphasis: 'highlight',
      exit: 'fade',
      easing: 'easeOut',
      duration: 300,
      delay: 10,
      scale: 1.0,
      activeScale: 1.04,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.3,
    },
    animationPreset: 'fade',
    density: 'relaxed',
  },

  'Social Viral': {
    presetName: 'Social Viral',
    category: 'Podcast',
    tagline: 'Clean white with bold drop shadow — Reels / Shorts optimized',
    tags: ['TikTok', 'Clean', 'Podcast'],
    fontFamily: 'Outfit, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#38BDF8',
    highlightColor: '#38BDF8',
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#000000',
    shadowBlur: 14,
    shadowOffsetX: 3,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#38BDF8',
    neonIntensity: 10,
    activeWordBackground: null,
    activeWordBgRadius: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'custom',
    horizontalPercent: 50,
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 82,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'karaoke',
    heroFontWeight: '900',
    activeWordScale: 1.15,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'punch',
      exit: 'fade',
      easing: 'bounce',
      duration: 160,
      delay: 20,
      scale: 0.88,
      activeScale: 1.15,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.7,
    },
    animationPreset: 'pop',
    density: 'compact',
  },

  // ───────────────────────── MISC (legacy compat) ──────────────────────────

  'Upper Dynamic': {
    presetName: 'Upper Dynamic',
    category: 'Trending',
    tagline: 'Electric blue spotlight gradient with drop shadow',
    tags: ['Reveal', 'Dynamic', 'Trending'],
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.8,
    lineSpacing: 1.18,
    textTransform: 'none',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    activeWordColor: '#3091F7',
    highlightColor: '#3091F7',
    outlineColor: '#000000',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 14,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasNeonGlow: true,
    neonColor: '#3091F7',
    neonIntensity: 18,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    position: 'left-chest',
    horizontalPercent: 22,
    verticalPositionPercent: 58,
    alignment: 'left',
    maxWidthPercent: 80,
    spotlightCase: 'uppercase',
    normalWordCase: 'sentence',
    highlightType: 'spotlight',
    heroFontWeight: '900',
    activeWordScale: 1.25,
    animation: {
      entrance: 'fade',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'premium',
      duration: 200,
      delay: 15,
      scale: 1.0,
      activeScale: 1.25,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.8,
    },
    animationPreset: 'smooth-fade',
    density: 'balanced',
  },

  'Electric Lime': {
    presetName: 'Electric Lime',
    category: 'Dynamic',
    tagline: 'Aggressive heavy Anton with neon green radiance',
    tags: ['MrBeast', 'Punchy', 'Dynamic'],
    fontFamily: 'Anton, sans-serif',
    fontSize: 38,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    textColor: '#10FF70',
    textOpacity: 1.0,
    activeWordColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#10FF70',
    shadowBlur: 18,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#10FF70',
    neonIntensity: 20,
    activeWordBackground: null,
    activeWordBgRadius: 6,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 6,
    position: 'middle',
    horizontalPercent: 50,
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'scale',
    heroFontWeight: '900',
    activeWordScale: 1.16,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'bounce',
      duration: 150,
      delay: 20,
      scale: 0.85,
      activeScale: 1.16,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.9,
    },
    animationPreset: 'bounce',
    density: 'compact',
  },

  'Golden Fire': {
    presetName: 'Golden Fire',
    category: 'Dynamic',
    tagline: 'Amber gold spotlight with flame aura',
    tags: ['Cinematic', 'Flame', 'Dynamic'],
    fontFamily: 'Bebas Neue, sans-serif',
    fontSize: 40,
    fontWeight: '400',
    letterSpacing: 2.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
    textColor: '#FFB800',
    textOpacity: 1.0,
    activeWordColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: '#FF4800',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#FF5500',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#FF6A00',
    neonIntensity: 22,
    activeWordBackground: null,
    activeWordBgRadius: 8,
    backgroundColor: '#130800',
    backgroundOpacity: 0.8,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    position: 'bottom',
    horizontalPercent: 50,
    verticalPositionPercent: 80,
    alignment: 'center',
    maxWidthPercent: 85,
    spotlightCase: 'uppercase',
    normalWordCase: 'uppercase',
    highlightType: 'spotlight',
    heroFontWeight: '700',
    activeWordScale: 1.2,
    animation: {
      entrance: 'scale-in',
      activeWord: 'scale-color',
      emphasis: 'neon-glow',
      exit: 'fade',
      easing: 'bounce',
      duration: 180,
      delay: 25,
      scale: 0.9,
      activeScale: 1.2,
      opacity: 0.0,
      translateY: 0,
      translateX: 0,
      rotation: 0,
      blur: 0,
      intensity: 0.9,
    },
    animationPreset: 'zoom',
    density: 'balanced',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// SAFE AREA PRESETS — Platform-specific caption safe zones
// ─────────────────────────────────────────────────────────────────────────────
export const SAFE_AREA_PRESETS = {
  tiktok: {
    label: 'TikTok',
    ratio: '9:16',
    captionZoneTop: 70,
    captionZoneBottom: 85,
    recommendedY: 78,
    maxWidthPercent: 85,
    note: 'Avoid TikTok UI: bottom 15% overlapped by buttons',
  },
  reels: {
    label: 'Instagram Reels',
    ratio: '9:16',
    captionZoneTop: 65,
    captionZoneBottom: 82,
    recommendedY: 75,
    maxWidthPercent: 85,
    note: 'Avoid Reels UI: bottom 18% overlapped',
  },
  shorts: {
    label: 'YouTube Shorts',
    ratio: '9:16',
    captionZoneTop: 60,
    captionZoneBottom: 80,
    recommendedY: 72,
    maxWidthPercent: 88,
    note: 'Shorts UI is minimal — more freedom',
  },
  youtube: {
    label: 'YouTube 16:9',
    ratio: '16:9',
    captionZoneTop: 78,
    captionZoneBottom: 92,
    recommendedY: 85,
    maxWidthPercent: 80,
    note: 'Standard bottom-third caption zone',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// UTILITY HELPERS
// ─────────────────────────────────────────────────────────────────────────────
export const formatSeconds = (seconds) => {
  if (isNaN(seconds) || seconds < 0) return '00:00:00.000';
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

export const parseTimestamp = (timeString) => {
  if (!timeString) return 0;
  const parts = timeString.split(':');
  if (parts.length === 3) {
    const hrs = parseFloat(parts[0]) || 0;
    const mins = parseFloat(parts[1]) || 0;
    const secs = parseFloat(parts[2]) || 0;
    return hrs * 3600 + mins * 60 + secs;
  }
  return parseFloat(timeString) || 0;
};

/** Returns the default preset (first in list) */
export const getDefaultPreset = () => STYLE_PRESETS['Hero Spotlight'];

/** Get all presets for a given category ('All' returns everything) */
export const getPresetsByCategory = (category = 'All') => {
  if (category === 'All') return Object.values(STYLE_PRESETS);
  return Object.values(STYLE_PRESETS).filter(p => p.category === category);
};

/** Merge a preset with user customizations — preserves user overrides */
export const mergeWithPreset = (preset, overrides = {}) => ({
  ...preset,
  ...overrides,
  animation: { ...(preset.animation || {}), ...(overrides.animation || {}) },
});
