export const STYLE_PRESETS = {
  'Hormozi Pop': {
    presetName: 'Hormozi Pop',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 34,
    fontWeight: '900',
    textColor: '#FFE600',
    textOpacity: 1.0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.9,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 10,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    hasNeonGlow: false,
    neonColor: '#FFE600',
    neonIntensity: 15,
    animationPreset: 'pop', // 'pop', 'bounce', 'fade', 'zoom', 'none'
    position: 'middle',
    verticalPositionPercent: 62,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 1.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
  },
  'Cyberpunk Neon': {
    presetName: 'Cyberpunk Neon',
    fontFamily: 'Russo One, sans-serif',
    fontSize: 32,
    fontWeight: '700',
    textColor: '#00F0FF',
    textOpacity: 1.0,
    backgroundColor: '#070a14',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 10,
    outlineColor: '#050515',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#00F0FF',
    shadowBlur: 20,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#00F0FF',
    neonIntensity: 22,
    animationPreset: 'pop',
    position: 'middle',
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.5,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
  },
  'Electric Lime': {
    presetName: 'Electric Lime',
    fontFamily: 'Anton, sans-serif',
    fontSize: 36,
    fontWeight: '800',
    textColor: '#10FF70',
    textOpacity: 1.0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 6,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#10FF70',
    shadowBlur: 18,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#10FF70',
    neonIntensity: 20,
    animationPreset: 'bounce',
    position: 'middle',
    verticalPositionPercent: 68,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.0,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
  },
  'Neon Magenta': {
    presetName: 'Neon Magenta',
    fontFamily: 'Poppins, sans-serif',
    fontSize: 32,
    fontWeight: '900',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    backgroundColor: '#16021f',
    backgroundOpacity: 0.8,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 12,
    outlineColor: '#FF007F',
    outlineWidth: 3,
    hasShadow: true,
    shadowColor: '#FF007F',
    shadowBlur: 25,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#FF007F',
    neonIntensity: 25,
    animationPreset: 'pop',
    position: 'bottom',
    verticalPositionPercent: 78,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 0.8,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
  },
  'Golden Fire': {
    presetName: 'Golden Fire',
    fontFamily: 'Bebas Neue, sans-serif',
    fontSize: 38,
    fontWeight: '400',
    textColor: '#FFB800',
    textOpacity: 1.0,
    backgroundColor: '#130800',
    backgroundOpacity: 0.75,
    hasBackgroundBox: true,
    backgroundPadding: 10,
    borderRadius: 8,
    outlineColor: '#FF4800',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#FF5500',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#FF6A00',
    neonIntensity: 20,
    animationPreset: 'zoom',
    position: 'bottom',
    verticalPositionPercent: 80,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 2.2,
    lineSpacing: 1.1,
    textTransform: 'uppercase',
  },
  'TikTok Viral': {
    presetName: 'TikTok Viral',
    fontFamily: 'Outfit, sans-serif',
    fontSize: 32,
    fontWeight: '800',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.0,
    hasBackgroundBox: false,
    backgroundPadding: 0,
    borderRadius: 0,
    outlineColor: '#000000',
    outlineWidth: 4,
    hasShadow: true,
    shadowColor: '#000000',
    shadowBlur: 12,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasNeonGlow: false,
    neonColor: '#00F0FF',
    neonIntensity: 10,
    animationPreset: 'pop',
    position: 'custom',
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 82,
    letterSpacing: 0.8,
    lineSpacing: 1.15,
    textTransform: 'uppercase',
  },
  'Classic Clean': {
    presetName: 'Classic Clean',
    fontFamily: 'Inter, sans-serif',
    fontSize: 26,
    fontWeight: '700',
    textColor: '#FFFFFF',
    textOpacity: 1.0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.65,
    hasBackgroundBox: true,
    backgroundPadding: 8,
    borderRadius: 6,
    outlineColor: '#000000',
    outlineWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.75)',
    shadowBlur: 6,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    hasNeonGlow: false,
    neonColor: '#FFFFFF',
    neonIntensity: 0,
    animationPreset: 'fade',
    position: 'bottom',
    verticalPositionPercent: 85,
    alignment: 'center',
    maxWidthPercent: 88,
    letterSpacing: 0.5,
    lineSpacing: 1.2,
    textTransform: 'none',
  },
  'Syne Velvet': {
    presetName: 'Syne Velvet',
    fontFamily: 'Syne, sans-serif',
    fontSize: 34,
    fontWeight: '800',
    textColor: '#E0E7FF',
    textOpacity: 1.0,
    backgroundColor: '#1E1B4B',
    backgroundOpacity: 0.9,
    hasBackgroundBox: true,
    backgroundPadding: 12,
    borderRadius: 16,
    outlineColor: '#6366F1',
    outlineWidth: 2,
    hasShadow: true,
    shadowColor: '#818CF8',
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasNeonGlow: true,
    neonColor: '#818CF8',
    neonIntensity: 20,
    animationPreset: 'pop',
    position: 'middle',
    verticalPositionPercent: 65,
    alignment: 'center',
    maxWidthPercent: 85,
    letterSpacing: 1.0,
    lineSpacing: 1.15,
    textTransform: 'none',
  }
};

export const formatSeconds = (seconds) => {
  if (isNaN(seconds) || seconds < 0) return '00:00:00.000';
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

export const parseTimestamp = (timeString) => {
  if (!timeString) return 0;
  const parts = timeString.split(':');
  if (parts.length === 3) {
    const hrs = parseFloat(parts[0]) || 0;
    const mins = parseFloat(parts[1]) || 0;
    const secs = parseFloat(parts[2]) || 0;
    return hrs * 3600 + mins * 60 + secs;
  }
  return parseFloat(timeString) || 0;
};
